- hosts: localhost
  connection: local
  collections:
    - vmware.ansible_for_nsxt
  
  tasks:
  - include_vars: NSXT_Variables.yml

  - name: Tag SSPi
    vmware.ansible_for_nsxt.nsxt_vm_tags:
      hostname: "{{ NSXT_CREDENTIALS.mgmt_node }}"
      username: "{{ NSXT_CREDENTIALS.username }}"
      password: "{{ NSXT_CREDENTIALS.password }}"
      validate_certs: False
      virtual_machine_display_name: "ssp-installer-01a"
      remove_other_tags: False
      add_tags:
        - scope: tier
          tag: APP
        - scope: environemnt
          tag: PROD
        - scope: application
          tag: SSPi
        - scope: zone
          tag: MGMT
        - scope: wld
          tag: W01

  - name: Get VM Names
    community.vmware.vmware_vm_info:
      hostname: "{{ VCENTER_CREDENTIALS.mgmt_node }}"
      username: "{{ VCENTER_CREDENTIALS.mgmt_username }}"
      password: "{{ VCENTER_CREDENTIALS.mgmt_password }}"
      validate_certs: False
    register: vm_info
  
  - name: Validate vm_names variable
    set_fact:
      ssp_workers: "{{ vm_info.virtual_machines | select('search','ssp-site-a-md') | selectattr('guest_name', 'defined') | map(attribute='guest_name') }}"
      ssp_controllers: "{{ vm_info.virtual_machines | select('search','ssp-site-a-cont') | selectattr('guest_name', 'defined') | map(attribute='guest_name') }}"

  - name: Tag SSP Controllers
    vmware.ansible_for_nsxt.nsxt_vm_tags:
      hostname: "{{ NSXT_CREDENTIALS.mgmt_node }}"
      username: "{{ NSXT_CREDENTIALS.username }}"
      password: "{{ NSXT_CREDENTIALS.password }}"
      validate_certs: False
      virtual_machine_display_name: "{{ item }}"
      remove_other_tags: False
      add_tags:
        - scope: tier
          tag: APP
        - scope: environemnt
          tag: PROD
        - scope: application
          tag: SSP
        - scope: zone
          tag: MGMT
        - scope: wld
          tag: W01
    loop: "{{ ssp_controllers }}"
  
  - name: Tag SSP Workers
    vmware.ansible_for_nsxt.nsxt_vm_tags:
      hostname: "{{ NSXT_CREDENTIALS.mgmt_node }}"
      username: "{{ NSXT_CREDENTIALS.username }}"
      password: "{{ NSXT_CREDENTIALS.password }}"
      validate_certs: False
      virtual_machine_display_name: "{{ item }}"
      remove_other_tags: False
      add_tags:
        - scope: tier
          tag: APP
        - scope: environemnt
          tag: PROD
        - scope: application
          tag: SSP
        - scope: zone
          tag: MGMT
        - scope: wld
          tag: W01
    loop: "{{ ssp_workers }}"

  - name: Update Security Group
    vmware.ansible_for_nsxt.nsxt_policy_group:
      hostname: "{{ NSXT_CREDENTIALS.node }}"
      username: "{{ NSXT_CREDENTIALS.username }}"
      password: "{{ NSXT_CREDENTIALS.password }}"
      state: "present"
      domain_id: "default"
      validate_certs: false
      display_name: M01_SSPM
      expression:
      - resource_type: IPAddressExpression
        ip_addresses:
        - 10.1.9.30-10.1.9.49
      id: M01_SSPM 